name: benchmark

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [bench]

permissions:
  contents: write # Allows this workflow to push to the gh-pages branch
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ python3 python3-pip
          pip3 install py-cpuinfo

      # Step 3: Build the speed_kem binary
      - name: Build speed_kem binary
        run: |
          mkdir -p build
          cd build
          cmake -GNinja .. -DBUILD_SHARED_LIBS=OFF
          ninja speed_kem

      # Step 4: Run the speed_kem test
      - name: Run speed_kem test
        run: |
          cd build/tests
          ./speed_kem > speed_kem_output.txt

      # Step 5: Parse the speed_kem results
      - name: Parse speed_kem results
        run: |
          python3 /home/pablo/Desktop/liboqs/scripts/parse_liboqs_speed.py build/tests/speed_kem_output.txt

      # Step 6: Upload the parsed results as an artifact
      - name: Upload parsed speed_kem results
        uses: actions/upload-artifact@v4
        with:
          name: parsed-speed-kem-results
          path: build/tests/speed_kem_output.json