name: benchmark

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [bench]

permissions:
  contents: write # Allows this workflow to push to the gh-pages branch
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ python3

      # Step 3: Build the project
      - name: Build speed_kem
        run: |
          mkdir -p build
          cd build
          cmake -GNinja .. -DBUILD_SHARED_LIBS=OFF
          ninja speed_kem

      # Step 4: Run the speed_kem test
      - name: Run speed_kem test
        run: |
          cd build/tests
          ./speed_kem > speed_kem_output.txt

      # Step 5: Upload the results as an artifact
      - name: Upload speed_kem results
        uses: actions/upload-artifact@v4
        with:
          name: speed-kem-results
          path: build/tests/speed_kem_output.txt

      # Step 6: Store benchmark results (optional)
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Speed KEM Benchmark
          tool: 'custom'
          output-file-path: build/tests/speed_kem_output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true