name: benchmark

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [bench]

permissions:
  deployments: write # Allows this workflow to to deploy to the gh-pages branch
  contents: write # Allows this workflow to push to the gh-pages branch
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algorithm: [
          "BIKE-L1", "BIKE-L3", "BIKE-L5",
          "Classic-McEliece-348864", "Classic-McEliece-348864f",
          "Classic-McEliece-460896", "Classic-McEliece-460896f",
          "Classic-McEliece-6688128", "Classic-McEliece-6688128f",
          "Classic-McEliece-6960119", "Classic-McEliece-6960119f",
          "Classic-McEliece-8192128", "Classic-McEliece-8192128f",
          "FrodoKEM-640-AES", "FrodoKEM-640-SHAKE",
          "FrodoKEM-976-AES", "FrodoKEM-976-SHAKE",
          "FrodoKEM-1344-AES", "FrodoKEM-1344-SHAKE"
        ]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ python3 python3-pip
          pip3 install py-cpuinfo

      # Build the speed_kem binary only
      - name: Build speed_kem binary
        run: |
          mkdir -p build
          cd build
          cmake -GNinja .. -DBUILD_SHARED_LIBS=OFF
          ninja speed_kem

      # Copy the parse_liboqs_speed.py script inside the directory where the binary speed_kem is located
      - name: Copy parse_liboqs_speed.py
        run: |
          cp scripts/parse_liboqs_speed.py build/tests/

      # Iterate through all algorithms and run tests
      - name: Run speed_kem tests for all algorithms
        run: |
          cd build/tests
          ./speed_kem "${{matrix.algorithm}}" > "${{matrix.algorithm}}_output.txt"
          python3 parse_liboqs_speed.py "${{matrix.algorithm}}_output.txt" --algorithm "${{matrix.algorithm}}"

      # Upload all parsed results as artifacts
      - name: Upload parsed speed_kem results
        uses: actions/upload-artifact@v4
        with:
          name: parsed-speed-kem-results
          path: build/tests/*_formatted.json

      # Push to GitHub pages using the continuous-benchmarking action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20.4
        with:
          name: ${{matrix.algorithm}}
          tool: "customSmallerIsBetter"
          output-file-path: build/tests/"${{matrix.algorithm}}_formatted.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          summary-always: true
          alert-threshold: 5%
          comment-always: true