name: constant-time-tooling

permissions:
    contents: read

on: [workflow_dispatch]

jobs:
    valgrind-varlat:
        runs-on: ubuntu-latest
        container:
            image: openquantumsafe/ci-ubuntu-latest:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

            - name: Install valgrind_varlat
              run: |
                cd ${{ github.workspace }}
                git clone https://sourceware.org/git/valgrind.git valgrind_varlat_src
                cd valgrind_varlat_src
                git checkout 112f1080b7c21e37dfce0a2e589d0dc7aa115afa
                git apply ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat/valgrind-try-patch-20250805.txt
                git apply ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-patch-20250805.txt
                git apply ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-sup-block.txt
                ./autogen.sh
                ./configure --prefix=${{ github.workspace }}/valgrind_varlat
                make -j$(nproc)
                make install
                mv "${{ github.workspace }}/bin/valgrind" "${{ github.workspace }}/bin/valgrind_varlat"
                echo "export PATH=\"${{ github.workspace }}/valgrind_varlat/bin:\$PATH\"" >> $GITHUB_ENV

            - name: Run valgrind_varlat tests
              run: |
                cd ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat
                chmod +x build.sh test.sh
                ./build.sh

            - name: Upload valgrind_varlat logs
              uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
              with: 
                name: valgrind_varlat logs
                path: |
                    ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat/logs/**

            - name: Generate visualizations and CSVs for valgrind_varlat
              run: |
                cd ${{ github.workspace }}/liboqs/tests/ct_tooling/scripts
                python3 ./analyze_results.py -t valgrind_varlat -i ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/valgrind_varlat/logs -o ${{ github.workspace }}/liboqs/tests/ct_tooling/results/valgrind_varlat
              
            - name: Upload visualizations and CSVs for valgrind_varlat
              uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
              with:
                name: valgrind_varlat visualizations and CSVs
                path: |
                    ${{ github.workspace }}/liboqs/tests/ct_tooling/results/valgrind_varlat

            
    
    memsan:
        runs-on: ubuntu-latest
        container:
            image: openquantumsafe/ci-ubuntu-latest:latest
        steps:
            - name: Checkout code
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

            - name: Run memsan tests
              run: |
                cd ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/memsan
                chmod +x build.sh test.sh
                ./build.sh

            - name: Upload memsan logs
              uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
              with: 
                name: memsan logs
                path: |
                    ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/memsan/logs/**

            - name: Generate visualizations and CSVs for memsan
              run: |
                cd ${{ github.workspace }}/liboqs/tests/ct_tooling/scripts
                python3 ./analyze_results.py -t memsan -i ${{ github.workspace }}/liboqs/tests/ct_tooling/tools/memsan/logs -o ${{ github.workspace }}/liboqs/tests/ct_tooling/results/memsan
              
            - name: Upload visualizations and CSVs for memsan
              uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
              with:
                name: memsan visualizations and CSVs
                path: |
                    ${{ github.workspace }}/liboqs/tests/ct_tooling/results/memsan