name: ct-tooling memsan

permissions:
  contents: read

on: [workflow_dispatch]

jobs:
  memsan:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    strategy:
      matrix:
        compiler: [clang]
        liboqs_build: [generic, auto]
        opt_flag: [-O1, -O2, -O3, -Os, -Ofast, "-O2 -fno-vectorize", "-O3 -fno-vectorize"]
        algorithm: 
          - BIKE-L1
          - Classic-McEliece-348864f
          - Kyber512
          - ML-KEM-512
          - FrodoKEM-640-AES
          - ML-DSA-44
          - Falcon-512
          - MAYO-1
          - cross-rsdp-128-balanced
          - OV-Is-pkc-skc
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Run memsan tests
        run: |
          cd "$GITHUB_WORKSPACE/tests/ct_tooling/tools/memsan"
          chmod +x ci_build.sh ci_test.sh
          ./ci_build.sh ${{ matrix.compiler }} ${{matrix.liboqs_build}} ${{ matrix.opt_flag }} ${{ matrix.algorithm }}

      - name: Upload memsan logs
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: memsan_${{ matrix.compiler }}_${{matrix.liboqs_build}}_${{ matrix.opt_flag }}_${{ matrix.algorithm }}_logs
          path: |
            tests/ct_tooling/tools/memsan/logs/**

    #   - name: Generate visualizations and CSVs for memsan
    #     run: |
    #       python3 -m ensurepip --upgrade
    #       python3 -m pip install --upgrade --user pip
    #       python3 -m pip install --user matplotlib
    #       cd "$GITHUB_WORKSPACE/tests/ct_tooling/scripts"
    #       python3 analyze_results.py \
    #         -t memsan \
    #         -i "$GITHUB_WORKSPACE/tests/ct_tooling/tools/memsan/logs" \
    #         -o "$GITHUB_WORKSPACE/tests/ct_tooling/results/memsan"

    #   - name: Upload visualizations and CSVs for memsan
    #     uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
    #     with:
    #       name: memsan visualizations and CSVs
    #       path: |
    #         $GITHUB_WORKSPACE/tests/ct_tooling/results/memsan