name: constant time tooling

permissions:
  contents: read

on: [workflow_dispatch]

jobs:

  build-valgrind-varlat:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Build valgrind_varlat
        run: |
          set -eux

          INSTALL_PREFIX="$PWD/valgrind_varlat"

          git clone https://sourceware.org/git/valgrind.git valgrind_varlat_src
          cd valgrind_varlat_src
          git checkout 112f1080b7c21e37dfce0a2e589d0dc7aa115afa

          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-try-patch-20250805.txt"
          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-patch-20250805.txt"
          git apply "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/valgrind-varlat-sup-block.txt"

          ./autogen.sh
          ./configure --prefix="$INSTALL_PREFIX"
          make -j"$(nproc)"
          make install

          mv "$INSTALL_PREFIX/bin/valgrind" \
             "$INSTALL_PREFIX/bin/valgrind_varlat"

      - name: Upload valgrind_varlat
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: valgrind_varlat
          path: valgrind_varlat

  valgrind-varlat:
    needs: build-valgrind-varlat
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        liboqs_build: [generic, auto]
        opt_flag: [-O0, -O1, -O2, -O3, -Os, -Ofast, "-O2 -fno-tree-vectorize", "-O3 -fno-tree-vectorize"]
    steps:

      - name: Download valgrind_varlat
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4
        with:
          name: valgrind_varlat
          path: .

      - name: Add valgrind_varlat to PATH
        run: |
            chmod +x "$GITHUB_WORKSPACE/valgrind_varlat/bin/valgrind_varlat"
            echo "$GITHUB_WORKSPACE/valgrind_varlat/bin" >> "$GITHUB_PATH"
            which valgrind_varlat

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Run valgrind_varlat tests
        run: |
          cd "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat"
          chmod +x build.sh test.sh
          ./build.sh ${{ matrix.compiler }} ${{matrix.liboqs_build}} ${{ matrix.opt_flag }}

      - name: Upload valgrind_varlat logs
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: valgrind_varlat logs
          path: |
            $GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/logs/**

    #   - name: Generate visualizations and CSVs for valgrind_varlat
    #     run: |
    #       python3 -m ensurepip --upgrade
    #       python3 -m pip install --upgrade --user pip
    #       python3 -m pip install --user matplotlib
    #       cd "$GITHUB_WORKSPACE/tests/ct_tooling/scripts"
    #       python3 analyze_results.py \
    #         -t valgrind_varlat \
    #         -i "$GITHUB_WORKSPACE/tests/ct_tooling/tools/valgrind_varlat/logs" \
    #         -o "$GITHUB_WORKSPACE/tests/ct_tooling/results/valgrind_varlat"

    #   - name: Upload visualizations and CSVs for valgrind_varlat
    #     uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
    #     with:
    #       name: valgrind_varlat visualizations and CSVs
    #       path: |
    #         $GITHUB_WORKSPACE/tests/ct_tooling/results/valgrind_varlat

  memsan:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    strategy:
      matrix:
        compiler: [clang]
        liboqs_build: [generic, auto]
        opt_flag: [-O1, -O2, -O3, -Os, -Ofast, "-O2 -fno-vectorize", "-O3 -fno-vectorize"]
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Run memsan tests
        run: |
          cd "$GITHUB_WORKSPACE/tests/ct_tooling/tools/memsan"
          chmod +x build.sh test.sh
          ./build.sh ${{ matrix.compiler }} ${{matrix.liboqs_build}} ${{ matrix.opt_flag }}

      - name: Upload memsan logs
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
        with:
          name: memsan logs
          path: |
            $GITHUB_WORKSPACE/tests/ct_tooling/tools/memsan/logs/**

    #   - name: Generate visualizations and CSVs for memsan
    #     run: |
    #       python3 -m ensurepip --upgrade
    #       python3 -m pip install --upgrade --user pip
    #       python3 -m pip install --user matplotlib
    #       cd "$GITHUB_WORKSPACE/tests/ct_tooling/scripts"
    #       python3 analyze_results.py \
    #         -t memsan \
    #         -i "$GITHUB_WORKSPACE/tests/ct_tooling/tools/memsan/logs" \
    #         -o "$GITHUB_WORKSPACE/tests/ct_tooling/results/memsan"

    #   - name: Upload visualizations and CSVs for memsan
    #     uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # pin@v4
    #     with:
    #       name: memsan visualizations and CSVs
    #       path: |
    #         $GITHUB_WORKSPACE/tests/ct_tooling/results/memsan