name: sig benchmark

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [bench]

permissions:
  deployments: write
  contents: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algorithm: [
          "Dilithium2",
          "Dilithium3",
          "Dilithium5",
          "ML-DSA-44",
          "ML-DSA-65",
          "ML-DSA-87",
          "Falcon-512",
          "Falcon-1024",
          "Falcon-padded-512",
          "Falcon-padded-1024",
          "SPHINCS+-SHA2-128f-simple",
          "SPHINCS+-SHA2-128s-simple",
          "SPHINCS+-SHA2-192f-simple",
          "SPHINCS+-SHA2-192s-simple",
          "SPHINCS+-SHA2-256f-simple",
          "SPHINCS+-SHA2-256s-simple",
          "SPHINCS+-SHAKE-128f-simple",
          "SPHINCS+-SHAKE-128s-simple",
          "SPHINCS+-SHAKE-192f-simple",
          "SPHINCS+-SHAKE-192s-simple",
          "SPHINCS+-SHAKE-256f-simple",
          "SPHINCS+-SHAKE-256s-simple",
          "MAYO-1",
          "MAYO-2",
          "MAYO-3",
          "MAYO-5",
          "cross-rsdp-128-balanced",
          "cross-rsdp-128-fast",
          "cross-rsdp-128-small",
          "cross-rsdp-192-balanced",
          "cross-rsdp-192-fast",
          "cross-rsdp-192-small",
          "cross-rsdp-256-balanced",
          "cross-rsdp-256-fast",
          "cross-rsdp-256-small",
          "cross-rsdpg-128-balanced",
          "cross-rsdpg-128-fast",
          "cross-rsdpg-128-small",
          "cross-rsdpg-192-balanced",
          "cross-rsdpg-192-fast",
          "cross-rsdpg-192-small",
          "cross-rsdpg-256-balanced",
          "cross-rsdpg-256-fast",
          "cross-rsdpg-256-small",
          "OV-Is",
          "OV-Ip",
          "OV-III",
          "OV-V",
          "OV-Is-pkc",
          "OV-Ip-pkc",
          "OV-III-pkc",
          "OV-V-pkc",
          "OV-Is-pkc-skc",
          "OV-Ip-pkc-skc",
          "OV-III-pkc-skc",
          "OV-V-pkc-skc"
        ]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc g++ python3 python3-pip
          pip3 install py-cpuinfo

      # Build the speed_sig binary only
      - name: Build speed_sig binary
        run: |
          mkdir -p build
          cd build
          cmake -GNinja .. -DBUILD_SHARED_LIBS=OFF
          ninja speed_sig

      # Copy the parse_liboqs_speed.py script inside the directory where the binary speed_sig is located
      - name: Copy parse_liboqs_speed.py
        run: |
          cp scripts/parse_liboqs_speed.py build/tests/

      # Iterate through all algorithms and run tests
      - name: Run speed_sig tests for all algorithms
        run: |
          cd build/tests
          ./speed_sig "${{matrix.algorithm}}" > ${{matrix.algorithm}}_output.txt
          python3 parse_liboqs_speed.py ${{matrix.algorithm}}_output.txt --algorithm ${{matrix.algorithm}}

      # Push to GitHub pages using the continuous-benchmarking action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20.4
        with:
          name: ${{matrix.algorithm}}
          tool: "customSmallerIsBetter"
          output-file-path: build/tests/${{matrix.algorithm}}_formatted.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          summary-always: true
          alert-threshold: 5%
          comment-always: true